name: Testing LLVM on MacOS

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/testMacOS.yml"
      - "build/**"
      - "lib/**"
      - "test/**"
      - "deno.json"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/testMacOS.yml"
      - "build/**"
      - "lib/**"
      - "test/**"
      - "deno.json"
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 1.30.0
    - name: install llvm@14
      run: brew install llvm@14
    - name: debug path
      run: brew --prefix llvm@14
    - name: list lib
      run: ls $(brew --prefix llvm@14)
    - name: list lib/lib
      run: ls $(brew --prefix llvm@14)/lib
    - name: run test no LIBCLANG_PATH
      run: |
        deno task test
    - name: run test LIBCLANG_PATH pointing to file
      run: |
        export LIBCLANG_PATH="$(brew --prefix llvm@14)/lib/libclang.dylib"
        deno task test
    - name: run test LIBCLANG_PATH pointing to directory
      run: |
        export LIBCLANG_PATH="$(brew --prefix llvm@14)/lib/"
        deno task test        