name: Testing LLVM on windows

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/testWindows.yml"
      - "build/**"
      - "lib/**"
      - "test/**"
      - "deno.json"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/testWindows.yml"
      - "build/**"
      - "lib/**"
      - "test/**"
      - "deno.json"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 1.30.0

    - name: Install LLVM
      run: |
        choco install -y --allow-downgrade --version 14.0.6 llvm

    # - name: add LLVM path to PATH environment variable
    #   uses: myci-actions/export-env-var-powershell@1
    #   with:
    #    name: PATH
    #    value: $env:PATH;$env:LIBCLANG_PATH
    - name: run test no LIBCLANG_PATH
      run: |
        deno task test

    - name: run test LIBCLANG_PATH pointing to file
      run: |
        $Env:LIBCLANG_PATH="C:\Program Files\LLVM\bin\libclang.dll"
        deno task test

    - name: run test LIBCLANG_PATH pointing to directory
      run: |
        $Env:LIBCLANG_PATH="C:\Program Files\LLVM\bin\"
        deno task test