name: Testing LLVM on Ubuntu

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/testUbuntu.yml"
      - "generator/**"
      - "lib/**"
      - "test/**"
      - "deno.json"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/testUbuntu.yml"
      - "generator/**"
      - "lib/**"
      - "test/**"
      - "deno.json"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 1.30.0

    # - name: Uninstall old LLVM
    #   run: |
    #     sudo apt-get remove -y libclang*

    - name: Install LLVM
      run: |
        sudo apt-get install -y libclang1-14 libclang-14-dev

    - name: run test no LIBCLANG_PATH
      run: |
        deno task test

    - name: run test LIBCLANG_PATH pointing to file
      run: |
        export LIBCLANG_PATH=/usr/lib/llvm-14/lib/libclang-14.so.1
        deno task test

    - name: run test LIBCLANG_PATH pointing to directory
      run: |
        export LIBCLANG_PATH=/usr/lib/llvm-14/lib/
        deno task test

    - name: Regen code LibClang
      run: |
        deno task genLibClang

    - name: check LibClang code
      run: |
        deno run generated/clang/ffi.ts

    # This step will evaluate the repo status and report the change
    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11

    # You can now access a variable indicating if there have been changes
    - name: Process changes
      if: steps.changes.outputs.changed == 1
      run: echo "Changes exist" && false